AWSTemplateFormatVersion: "2010-09-09"
Description: This builds subnets in the MFDPRODVPC.
Resources:
  AZACOREAPP102301520:
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs: ''
      CidrBlock: 10.230.152.0/23
      Tags:
      - Key: Name
        Value: AZ_A_CORE_APP_10.230.152.0
      - Key: Environment
        Value: MFD Production
      - Key: Permanence
        Value: Permenant
      - Key: Owner
        Value: Steve Coker
      - Key: Cost Center/Business Unit
        Value: BT-Networking
      - Key: Change Control
        Value: CHK112233
      - Key: Customer
        Value: DEN
      - Key: Public Or Private Facing
        Value: Private
      VpcId: 
        Fn::ImportValue: 
          !Sub MFDVPC-id
    Type: AWS::EC2::Subnet